title: Wenxi Liao
email: wenxi.liao@mail.mcgill.ca
description: blue-green infrastructure, water treatment, biochar, remote sensing and GIS, and urban ecosystem services.
url: "https://wenxiliao.github.io"
baseurl: ""   # keep empty for a user site

# Social (IDs/usernames only)
github_username: wenxiliao
scholar_userid: VB55UHsAAAAJ
orcid_id: 0000-0001-6600-4395
linkedin_username: wenxi-liao-phd-0b2a45122

remote_theme: academicpages/academicpages.github.io

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

# Useful site settings
permalink: /:categories/:title/
paginate: 5

# Navigation (just filenames inside _pages/)
nav_pages:
  - about.md
  - projects.md
  - people.md
  - publications.md
  - teaching.md
  - news.md
  - contact.md
