title: Wenxi Liao
email: wenxi.liao@mail.mcgill.ca
description: blue-green infrastructure, water treatment, biochar, remote sensing and GIS, and urban ecosystem services.
url: "https://wenxiliao.github.io"

# Social (fill what you use)
github_username: wenxiliao
scholar_userid: Wenxi Liao (https://scholar.google.ca/citations?hl=en&user=VB55UHsAAAAJ&view_op=list_works&sortby=pubdate)
orcid_id: 0000-0001-6600-4395
linkedin_username: Wenxi Liao (https://www.linkedin.com/in/wenxi-liao-phd-0b2a45122/)

# Navigation (we’ll add these pages below)
nav_pages:
  - about.md
  - projects.md
  - people.md
  - publications.md
  - teaching.md
  - news.md
  - contact.md
